/// <reference path="../ts/type/public.d.ts" />
import React from 'react';
import PropTypes from 'prop-types';
import Label from './component/label';
import Panel from './component/panel';
declare class ReactTabber extends React.Component<ReactTabber.Props, ReactTabber.State> {
    static Label: typeof Label;
    static Panel: typeof Panel;
    static propTypes: {
        tabs: PropTypes.Validator<(PropTypes.InferProps<{
            label: PropTypes.Validator<string | number | boolean | {} | PropTypes.ReactElementLike | PropTypes.ReactNodeArray>;
            panel: PropTypes.Validator<string | number | boolean | {} | PropTypes.ReactElementLike | PropTypes.ReactNodeArray>;
            key: PropTypes.Requireable<string | number>;
        }> | null)[]>;
        triggerEvents: PropTypes.Requireable<string | (string | null)[]>;
        delayTriggerEvents: PropTypes.Requireable<string | (string | null)[]>;
        delayTriggerCancelEvents: PropTypes.Requireable<string | (string | null)[]>;
        delayTriggerLatency: PropTypes.Requireable<number>;
        activeIndex: PropTypes.Requireable<number>;
        onSwitching: PropTypes.Requireable<(...args: any[]) => any>;
        onSwitched: PropTypes.Requireable<(...args: any[]) => any>;
        tabContainerClassName: PropTypes.Requireable<string>;
        labelContainerClassName: PropTypes.Requireable<string>;
        showHeaderLabelContainer: PropTypes.Requireable<boolean>;
        showFooterLabelContainer: PropTypes.Requireable<boolean>;
        headerLabelContainerClassName: PropTypes.Requireable<string>;
        footerLabelContainerClassName: PropTypes.Requireable<string>;
        labelItemClassName: PropTypes.Requireable<string>;
        labelItemActiveClassName: PropTypes.Requireable<string>;
        labelItemInactiveClassName: PropTypes.Requireable<string>;
        panelContainerClassName: PropTypes.Requireable<string>;
        panelItemClassName: PropTypes.Requireable<string>;
        panelItemActiveClassName: PropTypes.Requireable<string>;
        panelItemInactiveClassName: PropTypes.Requireable<string>;
    };
    static defaultProps: ReactTabber.Props;
    private activeIndex;
    private currentIndex;
    private renderedIndex;
    private triggerEvents?;
    private delayTriggerEvents?;
    private delayTriggerCancelEvents?;
    private delayTimeout?;
    constructor(props: any);
    componentWillReceiveProps(nextProps: ReactTabber.Props): void;
    componentWillMount(): void;
    componentWillUnmount(): void;
    private getValidIndex;
    private _createLabelContainer;
    private createHeaderLabelContainer;
    private createFooterLabelContainer;
    private createPanelContainer;
    private createTabContainer;
    private switchTo;
    private getTabEntries;
    render(): JSX.Element;
    private updateRenderedIndex;
    componentDidMount(): void;
    componentDidUpdate(): void;
}
export default ReactTabber;
